Add tile type and title to content validation errors
spectacles-ci/spectacles pull request #403
Opened 2021-08-30 17:22 UTC by DylanBaker

## Change description

When we raise a content validation error for a dashboard, it can be hard to know where the error is coming from in the dashboard as there can be many tiles and filters. This PR adds two new fields to the content validation error, one specifying whether it is a visualisation or filter, and another specifying the title of the visualisation or filter. This should make it easier to pinpoint where content validation errors are coming from. 

## Type of change
- [ ] Bug fix (fixes an issue)
- [X] New feature (adds functionality)

## Related issues

Closes #374  

## Checklists

### Security

- [x] Security impact of change has been considered
- [x] Code follows security best practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer

2021-09-01 18:45 UTC, joshtemple requested changes

2021-09-01 18:45 UTC, joshtemple commented on spectacles/validators/content.py
> +        print(self.project.get_results(validator="content"))
Guessing this needs to be deleted.

2021-09-02 16:27 UTC, DylanBaker commented on spectacles/validators/content.py
> +        print(self.project.get_results(validator="content"))
Yes. It does. Good catch.

2021-09-02 17:16 UTC, joshtemple approved these changes

2021-09-02 17:31 UTC, merged